language: python
python:
  - "3.7"
install:
  - pip install --upgrade pip
# command to run tests
script:
  - python -m  unittest discover -s  Database/sqlalchemy_create.py

branches:
  only:
    - master
    - development