language: python
python:
  - "3.7"
install:
  - pip install --upgrade pip
# command to run tests
script:
  - docker-compose up
  - docker-compose start
  - docker-compose stop
  - docker-compose down

branches:
  only:
    - master
    - development